# Generated by Django 4.1.2 on 2023-02-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(choices=[('1', 'Chelion Iberia'), ('2', 'Iberian Trade Europe')], default='1', max_length=1, verbose_name='business')),
                ('agent', models.CharField(choices=[('1', 'Mario'), ('2', 'Pablo'), ('3', 'Miguel Angel')], default='1', max_length=1, verbose_name='agent')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='address')),
                ('web', models.URLField(blank=True, null=True, verbose_name='web')),
                ('cif', models.CharField(max_length=20, verbose_name='CIF')),
                ('contact_person', models.CharField(max_length=200, verbose_name='contact person')),
                ('person_position', models.CharField(max_length=200, verbose_name='persons position')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('telephone', models.CharField(max_length=20, verbose_name='telephone')),
                ('a_installer', models.BooleanField(default=False, verbose_name='installer')),
                ('a_distributor', models.BooleanField(default=False, verbose_name='distributor')),
                ('a_meter', models.BooleanField(default=False, verbose_name='meter')),
                ('a_engineering', models.BooleanField(default=False, verbose_name='engineering')),
                ('i_storage', models.BooleanField(default=False, verbose_name='storage')),
                ('i_investor', models.BooleanField(default=False, verbose_name='investor')),
                ('i_charger', models.BooleanField(default=False, verbose_name='charger')),
                ('i_panels', models.BooleanField(default=False, verbose_name='panels')),
                ('i_others', models.BooleanField(default=False, verbose_name='others')),
                ('i_comment', models.TextField(blank=True, null=True, verbose_name='note')),
                ('interest', models.CharField(choices=[('1', 'Blue'), ('2', 'Yellow'), ('3', 'Red')], default='1', max_length=1, verbose_name='interest')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
            ],
        ),
    ]
