# Generated by Django 4.1.2 on 2023-02-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cif',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CIF'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='telephone'),
        ),
    ]
