# Generated by Django 4.1.2 on 2023-02-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_client_cif_alter_client_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='i_comment',
        ),
        migrations.AlterField(
            model_name='client',
            name='i_investor',
            field=models.BooleanField(default=False, verbose_name='inverter'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=200, verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='web',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='web'),
        ),
    ]
