# Generated by Django 4.1.2 on 2023-02-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_client_i_comment_alter_client_i_investor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='zipcode',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='CP'),
        ),
    ]
