# Generated by Django 4.1.2 on 2023-02-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_client_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='a_meter',
            field=models.BooleanField(default=False, verbose_name='EPC'),
        ),
        migrations.AlterField(
            model_name='client',
            name='zipcode',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='postal code'),
        ),
    ]
