# Generated by Django 4.1.2 on 2023-02-19 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_filespdf_client_new_user_alter_client_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='new_user',
            field=models.BooleanField(default=False, help_text='if check is a new client', verbose_name='new client'),
        ),
    ]
