# Generated by Django 4.1.2 on 2023-02-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_client_created_on_client_modified_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='agent',
            field=models.CharField(choices=[('1', 'None'), ('3', 'victor gonzalez'), ('5', 'Jarold Meléndez Lugo')], default='1', max_length=1, verbose_name='agent'),
        ),
        migrations.AlterField(
            model_name='client',
            name='business',
            field=models.CharField(choices=[('1', 'Chelion Iberia'), ('2', 'Iberian Trade Europe'), ('3', 'Ambos')], default='1', max_length=10, verbose_name='business'),
        ),
    ]
