# Generated by Django 4.1.2 on 2023-02-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_client_agent_alter_client_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='agent',
            field=models.CharField(choices=[('1', 'None'), ('3', 'victor gonzalez'), ('5', 'Jarold Meléndez Lugo')], default='1', max_length=10, verbose_name='agent'),
        ),
    ]
