# Generated by Django 4.1.2 on 2023-02-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_client_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='new_user',
            new_name='new_client',
        ),
    ]
