# Generated by Django 4.1.2 on 2023-02-19 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='backend.province', verbose_name='province'),
        ),
    ]
