# Generated by Django 4.1.2 on 2023-02-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_client_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created_on',
            field=models.DateTimeField(verbose_name='date of entry'),
        ),
    ]
